version: '3.8'

services:
  web:
    build: .
    #command: python /code/manage.py runserver 0.0.0.0:8000
    command: gunicorn blog_project.wsgi -b 0.0.0.0:8000
    environment:
      - SECRET_KEY=check_readme.md
      - DEBUG=1    
    volumes:
      - .:/code
    ports:
      - 8000:8000